pipeline{
    agent {
        label 'AGENT-1'
    }
    environment{
        appVersion= ''
        REGION= "us-east-1"
        ACC_ID= ""
        PROJECT= "roboshop"


    }
    options{
        timeout(time:30, unit:'MINUTES')
        disableConcurrentBuilds()
        ansiColour('xterm')
    }
    stages{
        stage('init'){
            steps{
                script{
                     withAWS(credentials:'AWS-creds', region: "${REGION}") {
                        sh """
                            cd 10-sg
                            terraform init -reconfigure
                        """
                    }
                }
            }
        }
        stage('Plan'){
            steps{
                script{
                     withAWS(credentials:'AWS-creds', region: "${REGION}") {
                        sh """
                            cd 10-sg
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('Apply'){
             input{
                message "should we countinue ?"
                ok "yes,we Should"
                submitter "Mr Jenkins"
            }
            steps{
                script{
                     withAWS(credentials:'AWS-creds', region: "${REGION}") {
                        sh """
                            cd 10-sg
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        stage('Trigger Bastion EKS ACM Parallel'){
            parallel {
                stage('Trigger Bastion'){
                    steps{
                        script{
                            build job: 'bastion'
                            propagate: false
                            wait: false
                        }
                    }
                }
                stage('Trigger ACM'){
                    steps{
                        script{
                            build job: 'acm'
                            propagate: false
                            wait: false
                        }
                    }
                }
                stage('Trigger EKS'){
                    steps{
                        script{
                            build job: 'eks'
                            propagate: false
                            wait: false
                        }
                    }
                }           
            }
        }
        stage('Trigger ALB'){
            steps{
                script{
                    build job: 'ingress-alb'
                    propagate: false
                    wait: false
                }
            }
        }

    }
    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success {
            echo 'Pipeline was Success'
        }
        failure {
            echo 'Pipeline was Failure'
        }
    }
}